
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.99
name: Task-Weaken
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.42
  File::Spec: 0.80
requires: 
  Scalar::Util: 1.14
  perl: 5.005
abstract: Ensure that a platform has weaken support
